### ISSUE TITLE
Cannot load YouTube video because YouTube player element ID required

### ISSUE THREAD

**Issue by jiyuujin** [NomNes/vue3-youtube#3]
Use vue3-youtube@0.1.6, but i cannot load YouTube video

There is an error below

```
Uncaught (in promise) Error: YouTube player element ID required.
```

**Comment by NomNes** [comment]
Sorry, I can't reproduce this error. It would be great if you gave more information (browser, os) and ideally - an example with this error

**Comment by bjcooper** [comment]
I'm seeing the same issue. I'll do a little digging for some reproduction criteria.

Windows version: 10.0.19044
Chrome version:  98.0.4758.82

**Comment by bjcooper** [comment]
OP didn't mention the stack trace, but for me the console error is:
```
www-widgetapi.js:897 Uncaught (in promise) Error: YouTube player element ID required.
    at pl.gl (www-widgetapi.js:897:121)
    at new pl (www-widgetapi.js:928:22)
    at Proxy.initPlayer (YouTube.vue?6574:118:21)
    at YouTube.vue?6574:97:34
```

**Comment by samsour** [comment]
Unfortunately this error still occurs
- MacOS Big Sur 11.4 (20F71)
- Chrome Version 100.0.4896.75
- Vue Version 3.2.16
- vue3-youtube 0.1.9
- Running a vite build on version 2.6.4 with the vue plugin on 1.9.3

Just tried out the first few lines of the documentation:
`<YouTube
	src="https://www.youtube.com/watch?v=jNQXAC9IVRw"
	@ready="onReady"
	ref="youtube"
/>`
Same error as @bjcooper.

**Comment by david-wb** [comment]
Same here. Anyone found a fix yet?

**Comment by Figumari** [comment]
Same here. 😢

**Comment by felixzapata** [comment]
same here. The weird is it was working for us until last Friday.

```
  System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 44.26 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5363.0
    Firefox: 105.0.3
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @intlify/core-base: 9.2.2 => 9.2.2 
    @intlify/unplugin-vue-i18n: 0.7.0 => 0.7.0 
    @vitejs/plugin-vue: 3.1.2 => 3.1.2 
    @vue/eslint-config-typescript: 11.0.2 => 11.0.2 
    @vue/test-utils: 2.1.0 => 2.1.0 
    @vue/tsconfig: 0.1.3 => 0.1.3 
    vite: 3.1.8 => 3.1.8 
    vitest: 0.24.1 => 0.24.1 
    vue: 3.2.40 => 3.2.40 
    vue-i18n: 9.2.2 => 9.2.2 
    vue-loader: 17.0.0 => 17.0.0 
    vue-router: 4.1.5 => 4.1.5 
    vue-tsc: 1.0.7 => 1.0.7 
    vue3-youtube: 0.1.9 => 0.1.9 
```

**Comment by DibPuelma** [comment]
Same error here

**Comment by mwiercioch** [comment]
same here

**Comment by richardajesus** [comment]
same here

Uncaught (in promise) Error: YouTube player element ID required.
    at Yr.Pr (www-widgetapi.js:1241:109)
    at new Yr (www-widgetapi.js:1277:22)
    at Proxy.initPlayer (vue3-youtube.umd.min.js:1:28677)
    at eval (vue3-youtube.umd.min.js:1:28221)

**Comment by moonwaystudio** [comment]
same here
